redis:
  host: "192.99.70.236"
  port: 6379
  password: "letsgetthefuckinjuice"
mongo:
  host: "192.99.70.236"
  port: 27017
  database: "admin"
  authentication:
    enabled: true
    username: "admin"
    password: "letsgetthefuckinjuice"
    database: "admin"